services:
  - type: web
    name: joyly-games
    runtime: node
    plan: free
    branch: main-1.0
    autoDeploy: true
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/config
    envVars:
      - key: NODE_ENV
        value: production
