// Generated by scripts/build-cosmic-trivia-director-cues.js.
// Edit content/games/cosmic-trivia/director/cues.json, then regenerate.

export const DIRECTOR_CUE_REGISTRY = {
  "version": 2,
  "gameId": "cosmic-trivia",
  "defaults": {
    "fallbackOrder": [
      "global.game.default"
    ]
  },
  "cues": [
    {
      "cueKey": "cross.game.final-question-armed",
      "scope": "cross",
      "domain": "game",
      "eventPath": [
        "final-question-armed"
      ],
      "purpose": "最后一题即将开始的跨阶段提醒",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "cross.game.final-question-armed.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/cross/game/final-question-armed/line-01.mp3",
          "text": "The final question is armed and probably wearing sunglasses.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "cross.game.final-question-ended",
      "scope": "cross",
      "domain": "game",
      "eventPath": [
        "final-question-ended"
      ],
      "purpose": "最后一题结束后的跨阶段提醒",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "cross.game.final-question-ended.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/cross/game/final-question-ended/line-01.mp3",
          "text": "The final question is done. Now we let suspense do its weird little dance.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "cross.stats.streak.2-question-wrong-streak",
      "scope": "cross",
      "domain": "stats",
      "eventPath": [
        "streak",
        "2-question-wrong-streak"
      ],
      "purpose": "连对两题",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "stats",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "cross.stats.streak.2-question-wrong-streak.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/cross/stats/streak/2-question-wrong-streak/line-01.mp3",
          "text": "Good job! Someone got 2 streaks",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "cross.stats.streak.2-question-wrong-streak.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/cross/stats/streak/2-question-wrong-streak/line-02.mp3",
          "text": "Vala! A steak!",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "cross.stats.streak.3-question-right-streak",
      "scope": "cross",
      "domain": "stats",
      "eventPath": [
        "streak",
        "3-question-right-streak"
      ],
      "purpose": "连对三题",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "stats",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "cross.stats.streak.3-question-right-streak.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/cross/stats/streak/3-question-right-streak/line-01.mp3",
          "text": "Someone has a streak going. I won't say who, but the scoreboard is whispering.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "cross.stats.streak.3-question-right-streak.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/cross/stats/streak/3-question-right-streak/line-02.mp3",
          "text": "Wow someone is on fire, watch out",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "cross.stats.streak.3-question-right-streak.line-03",
          "path": "/games/cosmic-trivia/audio/host/director/cross/stats/streak/3-question-right-streak/line-03.mp3",
          "text": "Oh ohh, come on, three times in a row?",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "cross.stats.streak.3-question-rightandwrong-streak",
      "scope": "cross",
      "domain": "stats",
      "eventPath": [
        "streak",
        "3-question-rightandwrong-streak"
      ],
      "purpose": "三连对和三连错同时触发",
      "policy": {},
      "trigger": {
        "mode": "phase-entry",
        "phase": "stats",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "cross.stats.streak.3-question-rightandwrong-streak.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/cross/stats/streak/3-question-rightandwrong-streak/line-01.mp3",
          "text": "Oh ohh while someone got a streak with the right answers, someone is wrong  3 times in a row....I won't mention names...but...hmmmm",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "cross.stats.streak.3-question-wrong-streak",
      "scope": "cross",
      "domain": "stats",
      "eventPath": [
        "streak",
        "3-question-wrong-streak"
      ],
      "purpose": "连错三题",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "stats",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "cross.stats.streak.3-question-wrong-streak.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/cross/stats/streak/3-question-wrong-streak/line-01.mp3",
          "text": "Oh ohh three times now",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "cross.stats.streak.4more-question-right-streak",
      "scope": "cross",
      "domain": "stats",
      "eventPath": [
        "streak",
        "4more-question-right-streak"
      ],
      "purpose": "连对四题以上",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "stats",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "cross.stats.streak.4more-question-right-streak.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/cross/stats/streak/4more-question-right-streak/line-01.mp3",
          "text": "Mammaaa, is on fire! [whisper] or Papi [laugh]",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "cross.stats.streak.detected",
      "scope": "cross",
      "domain": "stats",
      "eventPath": [
        "streak",
        "detected"
      ],
      "purpose": "连对两题（通用连胜提示）",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": []
    },
    {
      "cueKey": "global.connector.and",
      "scope": "global",
      "domain": "connector",
      "eventPath": [
        "and"
      ],
      "purpose": "过渡词，rank-1到rank-2之间",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "global.connector.and.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/global/connector/and/line-01.mp3",
          "text": "...and",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "global.connector.lastly",
      "scope": "global",
      "domain": "connector",
      "eventPath": [
        "lastly"
      ],
      "purpose": "过渡词，rank-2到rank-3之间",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "global.connector.lastly.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/global/connector/lastly/line-01.mp3",
          "text": "Lastly,",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "global.game.default",
      "scope": "global",
      "domain": "game",
      "eventPath": [
        "default"
      ],
      "purpose": "全局兜底口播",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "global.game.default.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/global/game/default/line-01.mp3",
          "text": "All right, space cadets, let's keep this quiz comet moving.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "global.score.hidden.started",
      "scope": "global",
      "domain": "score",
      "eventPath": [
        "hidden",
        "started"
      ],
      "purpose": "最后 30% 题目开始隐藏分数",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "global.score.hidden.started.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/global/score/hidden/started/line-01.mp3",
          "text": "From here on, scores are hidden. Suspense has entered the chat.",
          "placeholder": false,
          "regenerate": true
        },
        {
          "id": "global.score.hidden.started.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/global/score/hidden/started/line-02.mp3",
          "text": "The scoreboard is going undercover. You'll see the truth at the end.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.answer-lock.answer.locked",
      "scope": "phase",
      "domain": "answer-lock",
      "eventPath": [
        "answer",
        "locked"
      ],
      "purpose": "答案锁定",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "answer-lock",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.answer-lock.answer.locked.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answer-lock/answer/locked/line-01.mp3",
          "text": "Answers locked. Regret may now begin forming in a neat little line.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.answering.answer.all-in",
      "scope": "phase",
      "domain": "answering",
      "eventPath": [
        "answer",
        "all-in"
      ],
      "purpose": "所有人提前答完",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "answering",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.answering.answer.all-in.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answering/answer/all-in/line-01.mp3",
          "text": "Everyone answered. Look at that, a tiny miracle with Wi-Fi.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.answering.answer.all-in.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answering/answer/all-in/line-02.mp3",
          "text": "All answers are in. No more hiding behind strategic hesitation.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.answering.answer.open",
      "scope": "phase",
      "domain": "answering",
      "eventPath": [
        "answer",
        "open"
      ],
      "purpose": "进入答题",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "answering",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.answering.answer.open.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answering/answer/open/line-01.mp3",
          "text": "Answers are open. Tap your choice before your confidence changes its mind.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.answering.answer.open.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answering/answer/open/line-02.mp3",
          "text": "Choose wisely, or at least choose with theatrical commitment.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.answering.answer.open.line-03",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answering/answer/open/line-03.mp3",
          "text": "Lock in an answer on your phone. The universe accepts both knowledge and panic.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.answering.time.critical",
      "scope": "phase",
      "domain": "answering",
      "eventPath": [
        "time",
        "critical"
      ],
      "purpose": "答题最后几秒",
      "policy": {},
      "trigger": {
        "mode": "event-match",
        "phase": "answering",
        "eventKey": "phase.answering.time.critical",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.answering.time.critical.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answering/time/critical/line-01.mp3",
          "text": "Last seconds. Pick something and pretend it was a strategy.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.answering.time.critical.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answering/time/critical/line-02.mp3",
          "text": "Hurry up. Even the timer is starting to sweat.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.answering.time.warning",
      "scope": "phase",
      "domain": "answering",
      "eventPath": [
        "time",
        "warning"
      ],
      "purpose": "答题时间提醒",
      "policy": {},
      "trigger": {
        "mode": "event-match",
        "phase": "answering",
        "eventKey": "phase.answering.time.warning",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.answering.time.warning.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answering/time/warning/line-01.mp3",
          "text": "Time is getting dramatic. If you're still thinking, think faster.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.answering.time.warning.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/answering/time/warning/line-02.mp3",
          "text": "A few seconds left. This is your brain's final boarding call.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.between-questions.transition.next",
      "scope": "phase",
      "domain": "between-questions",
      "eventPath": [
        "transition",
        "next"
      ],
      "purpose": "题间转场",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "between-questions",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.between-questions.transition.next.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/between-questions/transition/next/line-01.mp3",
          "text": "Onward to the next question. Hydrate your brain if possible.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.between-questions.transition.next.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/between-questions/transition/next/line-02.mp3",
          "text": "Next question is warming up. It has been stretching backstage.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.final-hype.summary.best-streak",
      "scope": "phase",
      "domain": "final-hype",
      "eventPath": [
        "summary",
        "best-streak"
      ],
      "purpose": "最终揭晓前：连对统计",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "final-hype",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.final-hype.summary.best-streak.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/final-hype/summary/best-streak/line-01.mp3",
          "text": "Someone put together a streak tonight. I'm not naming names, but their ego knows.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.final-hype.summary.close-finish",
      "scope": "phase",
      "domain": "final-hype",
      "eventPath": [
        "summary",
        "close-finish"
      ],
      "purpose": "最终揭晓前：比分接近",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "final-hype",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.final-hype.summary.close-finish.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/final-hype/summary/close-finish/line-01.mp3",
          "text": "This finish is close enough to make the scoreboard breathe into a paper bag.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.final-hype.summary.everyone-missed",
      "scope": "phase",
      "domain": "final-hype",
      "eventPath": [
        "summary",
        "everyone-missed"
      ],
      "purpose": "最终揭晓前：某题无人答对",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "final-hype",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.final-hype.summary.everyone-missed.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/final-hype/summary/everyone-missed/line-01.mp3",
          "text": "One question completely wiped the room. A clean sweep, but rude.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.final-hype.summary.only-one-correct",
      "scope": "phase",
      "domain": "final-hype",
      "eventPath": [
        "summary",
        "only-one-correct"
      ],
      "purpose": "最终揭晓前：某题只有一人答对",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "final-hype",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.final-hype.summary.only-one-correct.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/final-hype/summary/only-one-correct/line-01.mp3",
          "text": "At one point, only one player got the answer right. Mysterious. Impressive. Slightly annoying.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.final-hype.summary.round-energy",
      "scope": "phase",
      "domain": "final-hype",
      "eventPath": [
        "summary",
        "round-energy"
      ],
      "purpose": "最终揭晓前：通用悬念总结",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "final-hype",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.final-hype.summary.round-energy.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/final-hype/summary/round-energy/line-01.mp3",
          "text": "This round had twists, turns, and at least one answer that looked legally questionable.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.finale.result.incoming",
      "scope": "phase",
      "domain": "finale",
      "eventPath": [
        "result",
        "incoming"
      ],
      "purpose": "最终结果公布前预热",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "finale",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.finale.result.incoming.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/finale/result/incoming/line-01.mp3",
          "text": "Final results are coming up. Please prepare your gracious winner face, just in case.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.finale.result.incoming.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/finale/result/incoming/line-02.mp3",
          "text": "Time for the final ranking. May the scoreboard be merciful and well-lit.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.game-setup.question-count.2nd-selection",
      "scope": "phase",
      "domain": "game-setup",
      "eventPath": [
        "question-count",
        "2nd-selection"
      ],
      "purpose": "Second time triggering question selection",
      "policy": {},
      "trigger": {
        "mode": "event-match",
        "phase": "game-setup",
        "eventKey": "phase.game-setup.question-count.2nd-selection",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.game-setup.question-count.2nd-selection.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/game-setup/question-count/2nd-selection/line-01.mp3",
          "text": "Changing the question count? Bold strategy. The quiz machine is pretending not to judge.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.game-setup.question-count.selection",
      "scope": "phase",
      "domain": "game-setup",
      "eventPath": [
        "question-count",
        "selection"
      ],
      "purpose": "题目数量选择阶段",
      "policy": {},
      "trigger": {
        "mode": "phase-entry",
        "phase": "game-setup",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.game-setup.question-count.selection.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/game-setup/question-count/selection/line-01.mp3",
          "text": "First up: how many questions are we launching into orbit?",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.game-setup.question-count.selection.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/game-setup/question-count/selection/line-02.mp3",
          "text": "Pick the question count, because apparently infinity was too many.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.intro",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "intro"
      ],
      "purpose": "引入偏好播报，语气期待，省略号留停顿",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.intro.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/intro/line-01.mp3",
          "text": "Based on your picks... here's what tonight looks like—",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.no-votes",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "no-votes"
      ],
      "purpose": "无人投票，轻松调侃，完全随机感",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.no-votes.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/no-votes/line-01.mp3",
          "text": "[chuckles] No strong preferences? Bold move. Anything could show up tonight.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-1.general",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-1",
        "general"
      ],
      "purpose": "综合类第一，调侃不可预测性",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-1.general.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-1/general/line-01.mp3",
          "text": "General knowledge taking the crown? [chuckles] Dangerous choice. Anything goes.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-1.geography",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-1",
        "geography"
      ],
      "purpose": "地理类第一，带点俏皮",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-1.geography.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-1/geography/line-01.mp3",
          "text": "[curious] Geography at the top... hope everyone's got their maps ready.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-1.history",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-1",
        "history"
      ],
      "purpose": "历史类第一，带点敬意和感慨",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-1.history.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-1/history/line-01.mp3",
          "text": "[thoughtful] History taking the lead... I love a crowd that knows its past.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-1.movies",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-1",
        "movies"
      ],
      "purpose": "电影类第一，兴奋感",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-1.movies.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-1/movies/line-01.mp3",
          "text": "Movies! [excited] The film buffs are absolutely in charge tonight.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-1.nature",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-1",
        "nature"
      ],
      "purpose": "自然类第一，温暖认可",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-1.nature.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-1/nature/line-01.mp3",
          "text": "Nature lovers are calling the shots tonight. [happy] Wholesome — I respect it.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-1.science",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-1",
        "science"
      ],
      "purpose": "科学类第一，调侃nerd能量",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-1.science.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-1/science/line-01.mp3",
          "text": "Looks like the science fans are running things tonight. [chuckles] Let's get nerdy.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-1.space",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-1",
        "space"
      ],
      "purpose": "太空类第一，惊喜加宇宙感",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-1.space.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-1/space/line-01.mp3",
          "text": "[surprised] Space and cosmos leading the way... we're going intergalactic tonight.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-1.sports",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-1",
        "sports"
      ],
      "purpose": "体育类第一，高能竞技感",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-1.sports.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-1/sports/line-01.mp3",
          "text": "Sports takes the top spot. [woo] Let's see if the athletes know their stats.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-2.general",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-2",
        "general"
      ],
      "purpose": "综合类第二，笑着认可",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-2.general.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-2/general/line-01.mp3",
          "text": "General knowledge also holding its own. [chuckles] The wild cards always show up.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-2.geography",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-2",
        "geography"
      ],
      "purpose": "地理类第二，微惊喜感",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-2.geography.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-2/geography/line-01.mp3",
          "text": "Geography pulling votes too. [surprised] The world travelers are representing.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-2.history",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-2",
        "history"
      ],
      "purpose": "历史类第二，沉稳跟进",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-2.history.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-2/history/line-01.mp3",
          "text": "History buffs making their presence known too. [thoughtful] A classic choice.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-2.movies",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-2",
        "movies"
      ],
      "purpose": "电影类第二，轻快愉悦",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-2.movies.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-2/movies/line-01.mp3",
          "text": "Movie lovers, you're not far behind. [happy] Cinema gets its moment.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-2.nature",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-2",
        "nature"
      ],
      "purpose": "自然类第二，温柔跟进",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-2.nature.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-2/nature/line-01.mp3",
          "text": "Nature quietly making its mark. [happy] A lovely addition to tonight's lineup.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-2.science",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-2",
        "science"
      ],
      "purpose": "科学类第二，认可科学粉丝",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-2.science.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-2/science/line-01.mp3",
          "text": "Science nerds, your voice is being heard. [chuckles] Solid pick.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-2.space",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-2",
        "space"
      ],
      "purpose": "太空类第二，带点好奇",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-2.space.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-2/space/line-01.mp3",
          "text": "Space enthusiasts are in the mix. [curious] The cosmos gets some airtime.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-2.sports",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-2",
        "sports"
      ],
      "purpose": "体育类第二，延续竞技感",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-2.sports.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-2/sports/line-01.mp3",
          "text": "Sports fans showing up strong as well. [excited] The competitive energy is real.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-3.general",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-3",
        "general"
      ],
      "purpose": "综合类第三，随性收尾",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-3.general.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-3/general/line-01.mp3",
          "text": "General knowledge at number three. [chuckles] The wild card always finds a way.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-3.geography",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-3",
        "geography"
      ],
      "purpose": "地理类第三，调侃地图控",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-3.geography.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-3/geography/line-01.mp3",
          "text": "Geography sneaking in at three. [curious] Map nerds, you found each other.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-3.history",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-3",
        "history"
      ],
      "purpose": "历史类第三，轻召唤感",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-3.history.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-3/history/line-01.mp3",
          "text": "History scholars, assemble. [thoughtful] Seems this one has a dedicated following.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-3.movies",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-3",
        "movies"
      ],
      "purpose": "电影类第三，安抚影迷",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-3.movies.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-3/movies/line-01.mp3",
          "text": "Film fans — you're not forgotten. [happy] Movies sneaks in at number three.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-3.nature",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-3",
        "nature"
      ],
      "purpose": "自然类第三，叹气带诗意",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-3.nature.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-3/nature/line-01.mp3",
          "text": "Nature has its gentle supporters. [sighs] This type always finds its people.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-3.science",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-3",
        "science"
      ],
      "purpose": "科学类第三，轻描淡写的nerd梗",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-3.science.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-3/science/line-01.mp3",
          "text": "Science nerds in the house... [chuckles] this one seems to have its quiet fans too.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-3.space",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-3",
        "space"
      ],
      "purpose": "太空类第三，轻柔宇宙感",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-3.space.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-3/space/line-01.mp3",
          "text": "The cosmos has its admirers. [curious] Space quietly pulling some interest tonight.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.interest-reveal.selection.rank-3.sports",
      "scope": "phase",
      "domain": "interest-reveal",
      "eventPath": [
        "selection",
        "rank-3",
        "sports"
      ],
      "purpose": "体育类第三，轻幽默",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "interest-reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.interest-reveal.selection.rank-3.sports.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/interest-reveal/selection/rank-3/sports/line-01.mp3",
          "text": "A few sports fans quietly raising their hand. [chuckles] Noted.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.post-game.result.outro",
      "scope": "phase",
      "domain": "post-game",
      "eventPath": [
        "result",
        "outro"
      ],
      "purpose": "赛后收尾",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "post-game",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.post-game.result.outro.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/post-game/result/outro/line-01.mp3",
          "text": "That's the game. You brought knowledge, guesses, and a surprising amount of confidence.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.post-game.result.outro.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/post-game/result/outro/line-02.mp3",
          "text": "Cosmic Trivia is complete. Please return all borrowed brain cells to the front desk.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.preferences.selection.done",
      "scope": "phase",
      "domain": "preferences",
      "eventPath": [
        "selection",
        "done"
      ],
      "purpose": "偏好选择完成",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "preferences",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.preferences.selection.done.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/preferences/selection/done/line-01.mp3",
          "text": "Preferences received. The question blender is now making science noises.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.preferences.selection.intro",
      "scope": "phase",
      "domain": "preferences",
      "eventPath": [
        "selection",
        "intro"
      ],
      "purpose": "玩家选择题材和关键词",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "preferences",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.preferences.selection.intro.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/preferences/selection/intro/line-01.mp3",
          "text": "Grab your phone and choose the topics you want to bravely overestimate yourself in.",
          "placeholder": false,
          "regenerate": true
        },
        {
          "id": "phase.preferences.selection.intro.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/preferences/selection/intro/line-02.mp3",
          "text": "Pick your favorite categories. The quiz machine is judging your taste, politely.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.question-intro.question.final",
      "scope": "phase",
      "domain": "question-intro",
      "eventPath": [
        "question",
        "final"
      ],
      "purpose": "最后一题前导",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "question-intro",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.question-intro.question.final.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/question-intro/question/final/line-01.mp3",
          "text": "Final question. This is where legends are made, and also where guesses wear tiny capes.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.question-intro.question.next",
      "scope": "phase",
      "domain": "question-intro",
      "eventPath": [
        "question",
        "next"
      ],
      "purpose": "题目前导",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "question-intro",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.question-intro.question.next.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/question-intro/question/next/line-01.mp3",
          "text": "Next question incoming. Eyes up, phones ready, dignity optional.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.question-intro.question.next.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/question-intro/question/next/line-02.mp3",
          "text": "Here comes the next one. Try to look like you meant to know this.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.question-intro.question.next.line-03",
          "path": "/games/cosmic-trivia/audio/host/director/phase/question-intro/question/next/line-03.mp3",
          "text": "Attention back to the screen. The quiz gremlin has selected another question.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.reveal.answer.3-correct",
      "scope": "phase",
      "domain": "reveal",
      "eventPath": [
        "answer",
        "3-correct"
      ],
      "purpose": "三人答对",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.reveal.answer.3-correct.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/reveal/answer/3-correct/line-01.mp3",
          "text": "3 players got it right [laugh] Not bad, noooot bad!",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.reveal.answer.4-correct",
      "scope": "phase",
      "domain": "reveal",
      "eventPath": [
        "answer",
        "4-correct"
      ],
      "purpose": "4人答对",
      "policy": {},
      "trigger": {
        "mode": "phase-entry",
        "phase": "reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.reveal.answer.4-correct.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/reveal/answer/4-correct/line-01.mp3",
          "text": "Ohhhhh 4 people got it right. [cheering]  Bring it in!",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.reveal.answer.only-two-correct",
      "scope": "phase",
      "domain": "reveal",
      "eventPath": [
        "answer",
        "only-two-correct"
      ],
      "purpose": "两人答对",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.reveal.answer.only-two-correct.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/reveal/answer/only-two-correct/line-01.mp3",
          "text": "Oh ohh, We have two correct anwsers.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.reveal.answer.everyone-correct",
      "scope": "phase",
      "domain": "reveal",
      "eventPath": [
        "answer",
        "everyone-correct"
      ],
      "purpose": "所有人答对",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.reveal.answer.everyone-correct.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/reveal/answer/everyone-correct/line-01.mp3",
          "text": "Everybody got it right. Suspiciously competent, all of you.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.reveal.answer.no-one-correct",
      "scope": "phase",
      "domain": "reveal",
      "eventPath": [
        "answer",
        "no-one-correct"
      ],
      "purpose": "无人答对",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.reveal.answer.no-one-correct.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/reveal/answer/no-one-correct/line-01.mp3",
          "text": "Nobody got it. The question wins this round and is being very smug about it.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.reveal.answer.no-one-correct.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/reveal/answer/no-one-correct/line-02.mp3",
          "text": "Not a single correct answer. Somewhere, trivia is cackling into a tiny microphone.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.reveal.answer.only-one-correct",
      "scope": "phase",
      "domain": "reveal",
      "eventPath": [
        "answer",
        "only-one-correct"
      ],
      "purpose": "只有一人答对",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.reveal.answer.only-one-correct.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/reveal/answer/only-one-correct/line-01.mp3",
          "text": "Only one player got that right. One hero, surrounded by confident fiction.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.reveal.answer.positive",
      "scope": "phase",
      "domain": "reveal",
      "eventPath": [
        "answer",
        "positive"
      ],
      "purpose": "公布正确答案常规口播",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "reveal",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.reveal.answer.positive.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/reveal/answer/positive/line-01.mp3",
          "text": "And the correct answer is... please act surprised if needed.",
          "placeholder": false,
          "regenerate": true
        },
        {
          "id": "phase.reveal.answer.positive.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/reveal/answer/positive/line-02.mp3",
          "text": "Let's reveal the answer and see whose confidence was accidentally correct.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.round-prep.round.loading",
      "scope": "phase",
      "domain": "round-prep",
      "eventPath": [
        "round",
        "loading"
      ],
      "purpose": "抽题和准备题组",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "round-prep",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.round-prep.round.loading.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/round-prep/round/loading/line-01.mp3",
          "text": "I'm assembling the round now. Please enjoy this brief moment of false confidence.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.round-prep.round.loading.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/round-prep/round/loading/line-02.mp3",
          "text": "Questions are loading. Somewhere, a spreadsheet just got very nervous.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.scoring.leader.new",
      "scope": "phase",
      "domain": "scoring",
      "eventPath": [
        "leader",
        "new"
      ],
      "purpose": "出现新的领先者",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "scoring",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.scoring.leader.new.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/scoring/leader/new/line-01.mp3",
          "text": "We have a new leader. The leaderboard just rearranged its furniture.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.scoring.leader.new.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/scoring/leader/new/line-02.mp3",
          "text": "First place has changed hands. Politely, but with consequences.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.scoring.rank.big-jump",
      "scope": "phase",
      "domain": "scoring",
      "eventPath": [
        "rank",
        "big-jump"
      ],
      "purpose": "有人排名大幅上升",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "scoring",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.scoring.rank.big-jump.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/scoring/rank/big-jump/line-01.mp3",
          "text": "Somebody just rocketed up the rankings. Please secure your loose expectations.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.scoring.score.hidden-update",
      "scope": "phase",
      "domain": "scoring",
      "eventPath": [
        "score",
        "hidden-update"
      ],
      "purpose": "隐藏分数期间的结算口播",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "scoring",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.scoring.score.hidden-update.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/scoring/score/hidden-update/line-01.mp3",
          "text": "Scores are changing behind the curtain. The curtain is feeling powerful.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    },
    {
      "cueKey": "phase.scoring.score.update",
      "scope": "phase",
      "domain": "scoring",
      "eventPath": [
        "score",
        "update"
      ],
      "purpose": "分数结算常规口播",
      "policy": {},
      "trigger": {
        "mode": "manual",
        "phase": "scoring",
        "eventKey": "",
        "priority": 100,
        "enabled": true
      },
      "variants": [
        {
          "id": "phase.scoring.score.update.line-01",
          "path": "/games/cosmic-trivia/audio/host/director/phase/scoring/score/update/line-01.mp3",
          "text": "Scores are updating. Please keep all victory dances inside the vehicle.",
          "placeholder": false,
          "regenerate": false
        },
        {
          "id": "phase.scoring.score.update.line-02",
          "path": "/games/cosmic-trivia/audio/host/director/phase/scoring/score/update/line-02.mp3",
          "text": "Points are being counted by highly trained imaginary interns.",
          "placeholder": false,
          "regenerate": false
        }
      ]
    }
  ]
};

export const DIRECTOR_CUES = DIRECTOR_CUE_REGISTRY.cues;

export const CUE_VARIANTS = Object.fromEntries(
  DIRECTOR_CUES.map(cue => [cue.cueKey, cue.variants.map(variant => variant.path).filter(Boolean)])
);
